#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This makes it easier for users to
# see which command caused the error.
F=$@
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
sudo apt-mark unhold linux-headers-6.6.20+rpt-common-rpi linux-headers-6.6.20+rpt-rpi-2712 linux-headers-6.6.20+rpt-rpi-v8 linux-image-6.6.20+rpt-rpi-2712 linux-image-6.6.20+rpt-rpi-v8 linux-kbuild-6.6.20+rpt
date
cd $HOME/sbitx
git stash
git pull
cd $HOME/sbitx/ft8_lib
make
sudo make install
cd ..
./build sbitx
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

echo "sbitx has been installed successfully. You can now close this window."
